name: your_project_name
description: A new Flutter project
version: 1.0.0

environment:
  sdk: '>=2.12.0 <=3.0.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Add other dependencies here
