name: Flutter for Android

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04

  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: flutter pub get

    - run: flutter build apk
    - run: flutter build appbundle


