name: Flutter for Android

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04

  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.19.5'
  

    - run: flutter create .
    
    - run: flutter pub get
    - run: flutter build apk -t main.dart 
    - run: flutter build appbundle


